---

- hosts: webservers
  tasks:
    - name: debug some information
      debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

    - name: print system vars
      debug:
        var: hostvars[inventory_hostname]["ansible_default_ipv4"]["gateway"]

    - shell: /usr/bin/uptime
      register: result

    - name: inject some vars
      debug:
        var: result
    
    