---
- hosts: webservers
  tasks:
  - name: debug2
    debug: msg="play2"
    notify:
      - debug1
      #- restart httpd
  
  #- include: task3.yml

  handlers:
    #- include: handlers.yml
    - name: debug1
      #debug: msg="Hello handlers!"
      service: name=httpd state=started
#- include: task1.yml