---
- hosts: all
  roles:
  - common

- hosts: dbservers
  user: root
  roles:
  - db

- hosts: webservers
  user: root
  roles:
  - base-apache
  - web

- hosts: lbservers
  user: root
  roles:
  - haproxy

- hosts: monitoring
  user: root
  roles:
  - base-apache
  - nagios

